### ISSUE TITLE
Missing user ID in README HTTP methods section

### ISSUE THREAD

**Issue by belgoros** [jcbvm/ember-api-requests#2]
If I'm not wrong, it seems that when you explain the available HTTP methods in the corresponding README section, you miss to precise the User `id`:
```
request('action', { model: 'user' }) // GET request to /users/action
request('action', { model: user })   // GET request to /users/1/action
```
where it would be wiser to add as for other cases:
```
asuming user is a model with id 1
```
What do you think ?

**Comment by jcbvm** [comment]
You are right, thanks for reporting!
